louvre_ticket_finalisationpage:
    path:    /finalisation/{code}
    defaults: { _controller: LOUVRETicketBundle:Finalisation:mail }
    
louvre_ticket_commandepage:
    path:    /commande/{code}
    defaults: { _controller: LOUVRETicketBundle:Paiement:commande }
    
louvre_ticket_reservationpage:
    path:    /reservation
    defaults: { _controller: LOUVRETicketBundle:Reservation:reservation }

louvre_ticket_remerciementpage:
    path:    /thanks
    defaults: { _controller: LOUVRETicketBundle:Remerciement:thanks }

louvre_ticket_annulerpage:
    path:    /delete/{code}
    defaults: { _controller: LOUVRETicketBundle:Reservation:delete }
    
    